# Generated by Django 3.0.7 on 2020-06-27 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 23, 18, 24, 250114)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='txt',
            field=models.TextField(default=datetime.datetime(2020, 6, 27, 23, 18, 24, 250114)),
        ),
    ]
